name: Deploy

on:
    push:
        branches:
        - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.21.0
            
            - name: Build
              run: go build -o main

            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                script: |
                    cd /home/ubuntu/go/src/github.com/your-username/your-repo
                    sudo systemctl stop your-service.service
                    sudo rm -rf /home/ubuntu/go/src/github.com/your-username/your-repo/*
                    sudo cp -r * /home/ubuntu/go/src/github.com/your-username/your-repo/

