name: Deploy

on:
    push:
        branches:
        - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.21.0
            
            - name: Build
              run: GOOS=linux GOARCH=amd64  go build  -ldflags="-s -w" -trimpath -o main main.go

            - name: 3、scp to cloud server
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_PASSWORD }}
                source: "main"
                target: "/tmp"

            - name: 4、deploy service
              uses: nekiro/ssh-job@main
              with:
                host: ${{ secrets.SSH_HOST }}
                password: ${{ secrets.SSH_PASSWORD }}
                user: ${{ secrets.SSH_USER }}
                #这里是执行脚本
                command: |
                  "pid=$(pgrep -f "main") && kill $pid && nohup /tmp/main &"    
          